<?php

namespace Database\Seeders;

use App\Models\Baladiya;
use App\Models\Wilaya;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds the 58 Algerian wilayas and their communes (baladiyas) with French and
 * Arabic names, following the post-2019 administrative reform (wilayas 49-58
 * carved out of the south).
 *
 * NOTE: this dataset is best-effort pending verification against the official
 * ONS commune list. Where a commune name has several transliterations in use,
 * the most common French spelling was preferred; a handful of names may need
 * correcting once checked against the official gazette.
 *
 * Safe to re-run: wilayas are upserted on (code), baladiyas on (wilaya_code, name_fr).
 */
class AlgeriaGeoSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::transaction(function () use ($now): void {
            $baladiyaRows = [];

            foreach (self::DATASET as $code => $wilaya) {
                Wilaya::query()->updateOrCreate(
                    ['code' => $code],
                    ['name_fr' => $wilaya['fr'], 'name_ar' => $wilaya['ar']],
                );

                foreach ($wilaya['communes'] as [$nameFr, $nameAr]) {
                    $baladiyaRows[] = [
                        'wilaya_code' => $code,
                        'name_fr' => $nameFr,
                        'name_ar' => $nameAr,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }
            }

            foreach (array_chunk($baladiyaRows, 250) as $chunk) {
                Baladiya::query()->upsert(
                    $chunk,
                    ['wilaya_code', 'name_fr'],
                    ['name_ar', 'updated_at'],
                );
            }
        });
    }

    /**
     * Wilaya code => ['fr' => name, 'ar' => name, 'communes' => [[fr, ar], ...]].
     *
     * @var array<int, array{fr: string, ar: string, communes: array<int, array{0: string, 1: string}>}>
     */
    private const DATASET = [
        1 => [
            'fr' => 'Adrar',
            'ar' => 'أدرار',
            'communes' => [
                ['Adrar', 'أدرار'],
                ['Tamest', 'تامست'],
                ['Reggane', 'رقان'],
                ['In Zghmir', 'إن زغمير'],
                ['Tit', 'تيت'],
                ['Tsabit', 'تسابيت'],
                ['Zaouiet Kounta', 'زاوية كنتة'],
                ['Aoulef', 'أولف'],
                ['Tamentit', 'تامنطيط'],
                ['Fenoughil', 'فنوغيل'],
                ['Sali', 'سالي'],
                ['Akabli', 'أقبلي'],
                ['Ouled Ahmed Timmi', 'أولاد أحمد تيمي'],
                ['Bouda', 'بودة'],
                ['Sbaa', 'السبع'],
                ['Timekten', 'تيمقتن'],
            ],
        ],
        2 => [
            'fr' => 'Chlef',
            'ar' => 'الشلف',
            'communes' => [
                ['Chlef', 'الشلف'],
                ['Ténès', 'تنس'],
                ['Bénairia', 'بنايرية'],
                ['El Karimia', 'الكريمية'],
                ['Tadjena', 'تاجنة'],
                ['Taougrite', 'تاوقريت'],
                ['Beni Haoua', 'بني حواء'],
                ['Sobha', 'صبحة'],
                ['Harchoun', 'حرشون'],
                ['Ouled Fares', 'أولاد فارس'],
                ['Sidi Akkacha', 'سيدي عكاشة'],
                ['Boukadir', 'بوقادير'],
                ['Beni Rached', 'بني راشد'],
                ['Talassa', 'تلعصة'],
                ['Herenfa', 'الهرانفة'],
                ['Oued Goussine', 'وادي قوسين'],
                ['Dahra', 'الظهرة'],
                ['Ouled Abbes', 'أولاد عباس'],
                ['Sendjas', 'سنجاس'],
                ['Zeboudja', 'الزبوجة'],
                ['Oued Sly', 'وادي سلي'],
                ['Abou El Hassan', 'أبو الحسن'],
                ['El Marsa', 'المرسى'],
                ['Chettia', 'الشطية'],
                ['Sidi Abderrahmane', 'سيدي عبد الرحمن'],
                ['Moussadek', 'مصدق'],
                ['El Hadjadj', 'الحجاج'],
                ['Labiod Medjadja', 'لبيض مجاجة'],
                ['Oued Fodda', 'وادي الفضة'],
                ['Ouled Ben Abdelkader', 'أولاد بن عبد القادر'],
                ['Bouzghaia', 'بوزغاية'],
                ['Aïn Merane', 'عين مران'],
                ['Oum Drou', 'أم الدروع'],
                ['Breira', 'بريرة'],
                ['Beni Bouattab', 'بني بوعتاب'],
            ],
        ],
        3 => [
            'fr' => 'Laghouat',
            'ar' => 'الأغواط',
            'communes' => [
                ['Laghouat', 'الأغواط'],
                ['Ksar El Hirane', 'قصر الحيران'],
                ['Bennasser Benchohra', 'بن ناصر بن شهرة'],
                ['Sidi Makhlouf', 'سيدي مخلوف'],
                ['Hassi Delaa', 'حاسي الدلاعة'],
                ["Hassi R'Mel", 'حاسي الرمل'],
                ['Aïn Madhi', 'عين ماضي'],
                ['Tadjemout', 'تاجموت'],
                ['El Kheneg', 'الخنق'],
                ['Gueltat Sidi Saad', 'قلتة سيدي سعد'],
                ['Aïn Sidi Ali', 'عين سيدي علي'],
                ['El Beidha', 'البيضاء'],
                ['Brida', 'بريدة'],
                ['El Ghicha', 'الغيشة'],
                ['Hadj Mechri', 'الحاج المشري'],
                ['Sebgag', 'سبقاق'],
                ['Taouiala', 'تاويالة'],
                ['Tadjrouna', 'تاجرونة'],
                ['Aflou', 'أفلو'],
                ['El Assafia', 'العسافية'],
                ['Oued Morra', 'وادي مرة'],
                ["Oued M'Zi", 'وادي مزي'],
                ['El Haouaita', 'الحويطة'],
                ['Sidi Bouzid', 'سيدي بوزيد'],
            ],
        ],
        4 => [
            'fr' => 'Oum El Bouaghi',
            'ar' => 'أم البواقي',
            'communes' => [
                ['Oum El Bouaghi', 'أم البواقي'],
                ['Aïn Beïda', 'عين البيضاء'],
                ["Aïn M'lila", 'عين مليلة'],
                ['Behir Chergui', 'بحير الشرقي'],
                ['El Amiria', 'العامرية'],
                ['Sigus', 'سيقوس'],
                ['El Belala', 'البلالة'],
                ['Aïn Babouche', 'عين ببوش'],
                ['Berriche', 'بريش'],
                ['Ouled Hamla', 'أولاد حملة'],
                ['Dhalaa', 'الضلعة'],
                ['Aïn Kercha', 'عين كرشة'],
                ['Hanchir Toumghani', 'هنشير تومغني'],
                ['El Djazia', 'الجازية'],
                ['Aïn Diss', 'عين الديس'],
                ['Fkirina', 'فكيرينة'],
                ['Souk Naamane', 'سوق نعمان'],
                ['Zorg', 'الزرق'],
                ['El Fedjoudj Boughrara Saoudi', 'الفجوج بوغرارة سعودي'],
                ['Ouled Zouaï', 'أولاد زواي'],
                ['Bir Chouhada', 'بئر الشهداء'],
                ['Ksar Sbahi', 'قصر الصباحي'],
                ['Oued Nini', 'وادي نيني'],
                ['Meskiana', 'مسكيانة'],
                ['Aïn Fakroun', 'عين فكرون'],
                ['Rahia', 'الرحية'],
                ['Aïn Zitoun', 'عين الزيتون'],
                ['Ouled Gacem', 'أولاد قاسم'],
                ['El Harmilia', 'الحرملية'],
            ],
        ],
        5 => [
            'fr' => 'Batna',
            'ar' => 'باتنة',
            'communes' => [
                ['Batna', 'باتنة'],
                ['Ghassira', 'غسيرة'],
                ['Maafa', 'معافة'],
                ['Merouana', 'مروانة'],
                ['Seriana', 'سريانة'],
                ['Menaa', 'منعة'],
                ['El Madher', 'المعذر'],
                ['Tazoult', 'تازولت'],
                ["N'Gaous", 'نقاوس'],
                ['Guigba', 'قيقبة'],
                ['Inoughissen', 'إينوغيسن'],
                ['Ouyoun El Assafir', 'عيون العصافير'],
                ['Djerma', 'جرمة'],
                ['Bitam', 'بيطام'],
                ['Azil Abdelkader', 'عزيل عبد القادر'],
                ['Arris', 'أريس'],
                ['Kimmel', 'كيمل'],
                ['Tilatou', 'تيلاطو'],
                ['Aïn Djasser', 'عين جاسر'],
                ['Ouled Sellam', 'أولاد سلام'],
                ['Tigherghar', 'تيغرغار'],
                ['Aïn Yagout', 'عين ياقوت'],
                ['Fesdis', 'فسديس'],
                ['Sefiane', 'سفيان'],
                ['Rahbat', 'الرحبات'],
                ['Tighanimine', 'تيغانمين'],
                ['Lemsane', 'لمسان'],
                ['Ksar Bellezma', 'قصر بلزمة'],
                ['Seggana', 'سقانة'],
                ['Ichmoul', 'إشمول'],
                ['Foum Toub', 'فم الطوب'],
                ['Beni Foudhala El Hakania', 'بني فضالة الحقانية'],
                ['Oued El Ma', 'وادي الماء'],
                ['Talkhamt', 'تالخمت'],
                ['Bouzina', 'بوزينة'],
                ['Chemora', 'الشمرة'],
                ['Oued Chaaba', 'وادي الشعبة'],
                ['Taxlent', 'تاكسلانت'],
                ['Gosbat', 'القصبات'],
                ['Ouled Aouf', 'أولاد عوف'],
                ['Boumagueur', 'بومقر'],
                ['Barika', 'بريكة'],
                ['Djezzar', 'الجزار'],
                ["T'Kout", 'تكوت'],
                ['Aïn Touta', 'عين التوتة'],
                ['Hidoussa', 'حيدوسة'],
                ['Teniet El Abed', 'ثنية العابد'],
                ['Oued Taga', 'وادي الطاقة'],
                ['Ouled Fadel', 'أولاد فاضل'],
                ['Timgad', 'تيمقاد'],
                ['Ras El Aioun', 'رأس العيون'],
                ['Chir', 'شير'],
                ['Ouled Si Slimane', 'أولاد سي سليمان'],
                ['Zana El Beida', 'زانة البيضاء'],
                ["M'Doukel", 'امدوكال'],
                ['Ouled Ammar', 'أولاد عمار'],
                ['El Hassi', 'الحاسي'],
                ['Lazrou', 'لازرو'],
                ['Boumia', 'بومية'],
                ['Boulhilat', 'بولهيلات'],
                ['Larbaâ', 'لارباع'],
            ],
        ],
        6 => [
            'fr' => 'Béjaïa',
            'ar' => 'بجاية',
            'communes' => [
                ['Béjaïa', 'بجاية'],
                ['Amizour', 'أميزور'],
                ['Ferraoun', 'فرعون'],
                ['Taourirt Ighil', 'تاوريرت إغيل'],
                ['Chellata', 'شلاطة'],
                ['Tamokra', 'تامقرة'],
                ['Timezrit', 'تيمزريت'],
                ['Souk El Tenine', 'سوق الاثنين'],
                ["M'Cisna", 'مسيسنة'],
                ['Tinebdar', 'تينبدار'],
                ['Tichy', 'تيشي'],
                ['Semaoun', 'سمعون'],
                ['Kendira', 'قنديرة'],
                ['Tifra', 'تيفرة'],
                ['Ighram', 'إغرم'],
                ['Amalou', 'أمالو'],
                ['Ighil Ali', 'إغيل علي'],
                ['Fenaia Ilmaten', 'فناية الماثن'],
                ['Toudja', 'توجة'],
                ['Darguina', 'درقينة'],
                ['Sidi Ayad', 'سيدي عياد'],
                ['Aokas', 'أوقاس'],
                ['Beni Djellil', 'بني جليل'],
                ['Adekar', 'أدكار'],
                ['Akbou', 'أقبو'],
                ['Seddouk', 'صدوق'],
                ['Tazmalt', 'تازمالت'],
                ["Aït R'Zine", 'آيت رزين'],
                ['Chemini', 'شميني'],
                ['Souk Oufella', 'سوق أوفلا'],
                ['Taskriout', 'تاسكريوت'],
                ['Tibane', 'طيبان'],
                ['Tala Hamza', 'تالة حمزة'],
                ['Barbacha', 'برباشة'],
                ['Beni Ksila', 'بني كسيلة'],
                ['Ouzellaguen', 'أوزلاقن'],
                ['Bouhamza', 'بوحمزة'],
                ['Beni Melikeche', 'بني مليكش'],
                ['Sidi Aïch', 'سيدي عيش'],
                ['El Kseur', 'القصر'],
                ['Melbou', 'ملبو'],
                ['Akfadou', 'أكفادو'],
                ['Leflaye', 'لفلاي'],
                ['Kherrata', 'خراطة'],
                ['Draâ El Kaïd', 'ذراع القايد'],
                ['Tamridjet', 'تامريجت'],
                ['Aït Smail', 'آيت سماعيل'],
                ['Boukhelifa', 'بوخليفة'],
                ["Tizi N'Berber", 'تيزي نبربر'],
                ['Beni Maouche', 'بني معوش'],
                ['Oued Ghir', 'وادي غير'],
                ['Boudjellil', 'بوجليل'],
            ],
        ],
        7 => [
            'fr' => 'Biskra',
            'ar' => 'بسكرة',
            'communes' => [
                ['Biskra', 'بسكرة'],
                ['Oumache', 'أوماش'],
                ['Branis', 'برانيس'],
                ['Chetma', 'شتمة'],
                ['Aïn Zaatout', 'عين زعطوط'],
                ['El Kantara', 'القنطرة'],
                ['Aïn Naga', 'عين الناقة'],
                ['Zeribet El Oued', 'زريبة الوادي'],
                ['El Feidh', 'الفيض'],
                ['El Outaya', 'لوطاية'],
                ['Djemorah', 'جمورة'],
                ['Tolga', 'طولقة'],
                ['Lioua', 'ليوة'],
                ['Lichana', 'ليشانة'],
                ['Ourlal', 'أورلال'],
                ['Mekhadma', 'مخادمة'],
                ['El Ghrous', 'الغروس'],
                ['El Hadjeb', 'الحاجب'],
                ['Foughala', 'فوغالة'],
                ['Bordj Ben Azzouz', 'برج بن عزوز'],
                ['Meziraa', 'مزيرعة'],
                ['Bouchagroune', 'بوشقرون'],
                ["M'Chouneche", 'مشونش'],
                ['El Haouch', 'الحوش'],
                ["M'Lili", 'امليلي'],
                ['Khanguet Sidi Nadji', 'خنقة سيدي ناجي'],
                ['Sidi Okba', 'سيدي عقبة'],
            ],
        ],
        8 => [
            'fr' => 'Béchar',
            'ar' => 'بشار',
            'communes' => [
                ['Béchar', 'بشار'],
                ['Boukais', 'بوكايس'],
                ['Mogheul', 'موغل'],
                ['Lahmar', 'لحمر'],
                ['Beni Ounif', 'بني ونيف'],
                ['Kenadsa', 'القنادسة'],
                ['Meridja', 'المريجة'],
                ['Taghit', 'تاغيت'],
                ['Abadla', 'العبادلة'],
                ['Mechraa Houari Boumediene', 'مشرع هواري بومدين'],
                ['Erg Ferradj', 'عرق فراج'],
                ['Tabelbala', 'تبلبالة'],
            ],
        ],
        9 => [
            'fr' => 'Blida',
            'ar' => 'البليدة',
            'communes' => [
                ['Blida', 'البليدة'],
                ['Chebli', 'الشبلي'],
                ['Bouinan', 'بوينان'],
                ['Oued El Alleug', 'وادي العلايق'],
                ['Ouled Yaïch', 'أولاد يعيش'],
                ['Chréa', 'الشريعة'],
                ['El Affroun', 'العفرون'],
                ['Chiffa', 'الشفة'],
                ['Hammam Melouane', 'حمام ملوان'],
                ['Ben Khelil', 'بن خليل'],
                ['Soumaa', 'الصومعة'],
                ['Mouzaia', 'موزاية'],
                ['Souhane', 'صوحان'],
                ['Meftah', 'مفتاح'],
                ['Ouled Selama', 'أولاد سلامة'],
                ['Boufarik', 'بوفاريك'],
                ['Larbaâ', 'الأربعاء'],
                ['Oued Djer', 'وادي جر'],
                ['Beni Tamou', 'بني تامو'],
                ['Bouarfa', 'بوعرفة'],
                ['Beni Mered', 'بني مراد'],
                ['Bougara', 'بوقرة'],
                ['Guerrouaou', 'قرواو'],
                ['Aïn Romana', 'عين الرمانة'],
                ['Djebabra', 'جبابرة'],
            ],
        ],
        10 => [
            'fr' => 'Bouira',
            'ar' => 'البويرة',
            'communes' => [
                ['Bouira', 'البويرة'],
                ['Aïn Bessem', 'عين بسام'],
                ['Aïn El Hadjar', 'عين الحجر'],
                ['Aïn El Turc', 'عين الترك'],
                ['Aïn Laloui', 'عين العلوي'],
                ['Aït Laaziz', 'آيت لعزيز'],
                ['Aghbalou', 'أغبالو'],
                ['Ahl El Ksar', 'أهل القصر'],
                ['Aomar', 'أعمر'],
                ['Ath Mansour', 'آث منصور'],
                ['Bechloul', 'بشلول'],
                ['Bir Ghbalou', 'بئر غبالو'],
                ['Bordj Okhriss', 'برج أوخريص'],
                ['Bouderbala', 'بودربالة'],
                ['Boukram', 'بوكرم'],
                ['Chorfa', 'الشرفاء'],
                ['Dechmia', 'الدشمية'],
                ['Dirah', 'ديرة'],
                ['Djebahia', 'جباحية'],
                ['El Adjiba', 'العجيبة'],
                ['El Asnam', 'الأصنام'],
                ['El Hachimia', 'الهاشمية'],
                ['El Hakimia', 'الحاكمية'],
                ['El Khebouzia', 'الخبوزية'],
                ['El Mokrani', 'المقراني'],
                ['Guerrouma', 'قرومة'],
                ['Hadjera Zerga', 'الحجرة الزرقاء'],
                ['Haizer', 'حيزر'],
                ['Hanif', 'حنيف'],
                ['Kadiria', 'قادرية'],
                ['Lakhdaria', 'الأخضرية'],
                ['Maala', 'معلة'],
                ['Maamora', 'المعمورة'],
                ["M'Chedallah", 'مشد الله'],
                ['Mezdour', 'مزدور'],
                ['Oued El Berdi', 'وادي البردي'],
                ['Ouled Rached', 'أولاد راشد'],
                ['Raouraoua', 'روراوة'],
                ['Ridane', 'ريدان'],
                ['Saharidj', 'سحاريج'],
                ['Souk El Khemis', 'سوق الخميس'],
                ['Sour El Ghozlane', 'سور الغزلان'],
                ['Taghzout', 'تاغزوت'],
                ['Taguedit', 'تاقديت'],
                ['Zbarbar', 'زبربر'],
            ],
        ],
        11 => [
            'fr' => 'Tamanrasset',
            'ar' => 'تمنراست',
            'communes' => [
                ['Tamanrasset', 'تمنراست'],
                ['Abalessa', 'أبلسة'],
                ['Idles', 'إدلس'],
                ['Tazrouk', 'تاظروك'],
                ['In Amguel', 'عين أمقل'],
            ],
        ],
        12 => [
            'fr' => 'Tébessa',
            'ar' => 'تبسة',
            'communes' => [
                ['Tébessa', 'تبسة'],
                ['Bir El Ater', 'بئر العاتر'],
                ['Cheria', 'الشريعة'],
                ['Stah Guentis', 'سطح قنطيس'],
                ['El Aouinet', 'العوينات'],
                ['Lahouidjbet', 'الحويجبات'],
                ['Safsaf El Ouesra', 'صفصاف الوسرى'],
                ['Hammamet', 'الحمامات'],
                ['Negrine', 'نقرين'],
                ['Bir Mokkadem', 'بئر مقدم'],
                ['El Kouif', 'الكويف'],
                ['Morsott', 'مرسط'],
                ['El Ogla', 'العقلة'],
                ['Bir Dheheb', 'بئر الذهب'],
                ['El Ogla El Malha', 'العقلة المالحة'],
                ['Gorriguer', 'قريقر'],
                ['Bekkaria', 'بكارية'],
                ['Boukhadra', 'بوخضرة'],
                ['Ouenza', 'الونزة'],
                ['El Ma El Biodh', 'الماء الأبيض'],
                ['Oum Ali', 'أم علي'],
                ['Thlidjene', 'ثليجان'],
                ['Aïn Zerga', 'عين الزرقاء'],
                ['El Meridj', 'المريج'],
                ['Boulhaf Dyr', 'بولحاف الدير'],
                ['Bedjene', 'بجن'],
                ['El Mazeraa', 'المزرعة'],
                ['Ferkane', 'فركان'],
            ],
        ],
        13 => [
            'fr' => 'Tlemcen',
            'ar' => 'تلمسان',
            'communes' => [
                ['Tlemcen', 'تلمسان'],
                ['Beni Mester', 'بني مستر'],
                ['Aïn Tallout', 'عين تالوت'],
                ['Remchi', 'الرمشي'],
                ['El Fehoul', 'الفحول'],
                ['Sabra', 'صبرة'],
                ['Ghazaouet', 'الغزوات'],
                ['Souani', 'السواني'],
                ['Djebala', 'جبالة'],
                ['El Gor', 'القور'],
                ['Oued Lakhdar', 'وادي الأخضر'],
                ['Aïn Fezza', 'عين فزة'],
                ['Ouled Mimoun', 'أولاد ميمون'],
                ['Amieur', 'عمير'],
                ['Aïn Youcef', 'عين يوسف'],
                ['Zenata', 'زناتة'],
                ['Beni Snous', 'بني سنوس'],
                ['Bab El Assa', 'باب العسة'],
                ['Dar Yaghmouracene', 'دار يغمراسن'],
                ['Fellaoucene', 'فلاوسن'],
                ['Azails', 'العزايل'],
                ['Sebbaa Chioukh', 'سبعة شيوخ'],
                ['Terny Beni Hediel', 'تيرني بني هديل'],
                ['Bensekrane', 'بن سكران'],
                ['Aïn Nehala', 'عين النحالة'],
                ['Hennaya', 'الحناية'],
                ['Maghnia', 'مغنية'],
                ['Hammam Boughrara', 'حمام بوغرارة'],
                ['Souahlia', 'السواحلية'],
                ['Msirda Fouaga', 'مسيردة الفواقة'],
                ['Aïn Fetah', 'عين فتاح'],
                ['El Aricha', 'العريشة'],
                ['Souk Thlata', 'سوق الثلاثاء'],
                ['Sidi Abdelli', 'سيدي العبدلي'],
                ['Sebdou', 'سبدو'],
                ['Beni Ouarsous', 'بني وارسوس'],
                ['Sidi Medjahed', 'سيدي مجاهد'],
                ['Beni Boussaid', 'بني بوسعيد'],
                ["Marsa Ben M'Hidi", 'مرسى بن مهيدي'],
                ['Nedroma', 'ندرومة'],
                ['Sidi Djillali', 'سيدي الجيلالي'],
                ['Beni Bahdel', 'بني بهدل'],
                ['El Bouihi', 'البويهي'],
                ['Honaine', 'هنين'],
                ['Tianet', 'تيانت'],
                ['Ouled Riyah', 'أولاد رياح'],
                ['Bouhlou', 'بوحلو'],
                ['Beni Khellad', 'بني خلاد'],
                ['Aïn Ghoraba', 'عين غرابة'],
                ['Chetouane', 'شتوان'],
                ['Mansourah', 'المنصورة'],
                ['Beni Semiel', 'بني صميل'],
                ['Aïn Kebira', 'عين الكبيرة'],
            ],
        ],
        14 => [
            'fr' => 'Tiaret',
            'ar' => 'تيارت',
            'communes' => [
                ['Tiaret', 'تيارت'],
                ['Medroussa', 'مدروسة'],
                ['Aïn Bouchekif', 'عين بوشقيف'],
                ['Sidi Ali Mellal', 'سيدي علي ملال'],
                ['Aïn Zarit', 'عين زاريت'],
                ['Aïn Deheb', 'عين الذهب'],
                ['Sidi Bakhti', 'سيدي بختي'],
                ['Medrissa', 'مدريسة'],
                ['Zmalet El Emir Abdelkader', 'زمالة الأمير عبد القادر'],
                ['Madna', 'مادنة'],
                ['Sebt', 'السبت'],
                ['Mellakou', 'ملاكو'],
                ['Dahmouni', 'الدحموني'],
                ['Rahouia', 'الرحوية'],
                ['Mahdia', 'مهدية'],
                ['Sougueur', 'السوقر'],
                ['Sidi Abdelghani', 'سيدي عبد الغني'],
                ['Aïn El Hadid', 'عين الحديد'],
                ['Ouled Djerad', 'أولاد جراد'],
                ['Naima', 'النعيمة'],
                ['Meghila', 'مغيلة'],
                ['Guertoufa', 'قرطوفة'],
                ['Sidi Hosni', 'سيدي حسني'],
                ['Djillali Ben Amar', 'جيلالي بن عمار'],
                ['Sebaine', 'سبعين'],
                ['Tousnina', 'توسنينة'],
                ['Frenda', 'فرندة'],
                ['Aïn Kermes', 'عين كرمس'],
                ['Ksar Chellala', 'قصر الشلالة'],
                ['Rechaiga', 'الرشايقة'],
                ['Nadorah', 'الناظورة'],
                ['Tagdemt', 'تاقدمت'],
                ['Oued Lilli', 'وادي ليلي'],
                ['Mechraa Safa', 'مشرع الصفا'],
                ['Hamadia', 'حمادية'],
                ['Chehaima', 'الشحيمة'],
                ['Takhemaret', 'تاخمرت'],
                ['Sidi Abderrahmane', 'سيدي عبد الرحمن'],
                ['Serghine', 'سرغين'],
                ['Bougara', 'بوقرة'],
                ['Faidja', 'الفايجة'],
                ['Tidda', 'تيدة'],
            ],
        ],
        15 => [
            'fr' => 'Tizi Ouzou',
            'ar' => 'تيزي وزو',
            'communes' => [
                ['Tizi Ouzou', 'تيزي وزو'],
                ['Aïn El Hammam', 'عين الحمام'],
                ['Akbil', 'أقبيل'],
                ['Freha', 'فريحة'],
                ['Souamaa', 'صوامع'],
                ['Mechtras', 'مشطراس'],
                ['Irdjen', 'إرجن'],
                ['Timizart', 'تيميزار'],
                ['Makouda', 'ماكودة'],
                ['Draâ El Mizan', 'ذراع الميزان'],
                ['Tizi Ghenif', 'تيزي غنيف'],
                ['Bounouh', 'بونوح'],
                ['Aït Chafaa', 'آيت شافع'],
                ['Frikat', 'فريقات'],
                ['Beni Aïssi', 'بني عيسي'],
                ['Beni Zmenzer', 'بني زمنزر'],
                ['Iferhounene', 'إفرحونن'],
                ['Azazga', 'عزازقة'],
                ['Iloula Oumalou', 'إيلولة أومالو'],
                ['Yakouren', 'إعكورن'],
                ['Larbaâ Nath Irathen', 'الأربعاء ناث إيراثن'],
                ['Tizi Rached', 'تيزي راشد'],
                ['Zekri', 'زكري'],
                ['Ouaguenoun', 'واقنون'],
                ['Aïn Zaouia', 'عين الزاوية'],
                ["M'Kira", 'مكيرة'],
                ['Aït Yahia', 'آيت يحيى'],
                ['Aït Mahmoud', 'آيت محمود'],
                ['Maatkas', 'معاتقة'],
                ['Aït Boumahdi', 'آيت بومهدي'],
                ['Abi Youcef', 'أبي يوسف'],
                ['Beni Douala', 'بني دوالة'],
                ['Illilten', 'إيليلتن'],
                ['Bouzeguene', 'بوزقن'],
                ['Aït Aggouacha', 'آيت عقواشة'],
                ['Ouadhias', 'واضية'],
                ['Azeffoun', 'أزفون'],
                ['Tigzirt', 'تيقزيرت'],
                ['Aït Aïssa Mimoun', 'آيت عيسى ميمون'],
                ['Boghni', 'بوغني'],
                ['Ifigha', 'إفيغاء'],
                ['Aït Oumalou', 'آيت أومالو'],
                ['Tirmitine', 'تيرمتين'],
                ['Akerrou', 'أقرو'],
                ['Yatafen', 'يطافن'],
                ['Beni Ziki', 'بني زيكي'],
                ['Draâ Ben Khedda', 'ذراع بن خدة'],
                ['Ouacifs', 'واسيف'],
                ['Idjeur', 'إجعر'],
                ['Mekla', 'مقلع'],
                ["Tizi N'Tleta", 'تيزي نثلاثة'],
                ['Beni Yenni', 'بني يني'],
                ['Aghribs', 'أغريب'],
                ['Iflissen', 'إفليسن'],
                ['Boudjima', 'بوجيمة'],
                ['Aït Yahia Moussa', 'آيت يحيى موسى'],
                ['Souk El Thenine', 'سوق الاثنين'],
                ['Aït Khelili', 'آيت خليلي'],
                ['Sidi Naamane', 'سيدي نعمان'],
                ['Iboudraren', 'إبودرارن'],
                ['Agouni Gueghrane', 'أقني قغران'],
                ['Mizrana', 'ميزرانة'],
                ['Imsouhal', 'إمسوحال'],
                ['Tadmait', 'تادمايت'],
                ['Aït Bouaddou', 'آيت بوادو'],
                ['Assi Youcef', 'آسي يوسف'],
                ['Aït Toudert', 'آيت توضرت'],
            ],
        ],
        16 => [
            'fr' => 'Alger',
            'ar' => 'الجزائر',
            'communes' => [
                ['Alger Centre', 'الجزائر الوسطى'],
                ["Sidi M'Hamed", 'سيدي امحمد'],
                ['El Madania', 'المدنية'],
                ['Belouizdad', 'بلوزداد'],
                ['Bab El Oued', 'باب الوادي'],
                ['Bologhine', 'بولوغين'],
                ['Casbah', 'القصبة'],
                ['Oued Koriche', 'وادي قريش'],
                ['Bir Mourad Raïs', 'بئر مراد رايس'],
                ['El Biar', 'الأبيار'],
                ['Bouzareah', 'بوزريعة'],
                ['Birkhadem', 'بئر خادم'],
                ['El Harrach', 'الحراش'],
                ['Baraki', 'براقي'],
                ['Oued Smar', 'وادي السمار'],
                ['Bourouba', 'بوروبة'],
                ['Hussein Dey', 'حسين داي'],
                ['Kouba', 'القبة'],
                ['Bachdjerrah', 'باش جراح'],
                ['Dar El Beïda', 'الدار البيضاء'],
                ['Bab Ezzouar', 'باب الزوار'],
                ['Ben Aknoun', 'بن عكنون'],
                ['Dely Ibrahim', 'دالي إبراهيم'],
                ['Hammamet', 'الحمامات'],
                ['Raïs Hamidou', 'رايس حميدو'],
                ['Djasr Kasentina', 'جسر قسنطينة'],
                ['El Mouradia', 'المرادية'],
                ['Hydra', 'حيدرة'],
                ['Mohammadia', 'المحمدية'],
                ['Bordj El Kiffan', 'برج الكيفان'],
                ['El Magharia', 'المغارية'],
                ['Beni Messous', 'بني مسوس'],
                ['Les Eucalyptus', 'الكاليتوس'],
                ['Birtouta', 'بئر توتة'],
                ['Tessala El Merdja', 'تسالة المرجة'],
                ['Ouled Chebel', 'أولاد الشبل'],
                ['Sidi Moussa', 'سيدي موسى'],
                ['Aïn Taya', 'عين طاية'],
                ['Bordj El Bahri', 'برج البحري'],
                ['El Marsa', 'المرسى'],
                ["H'Raoua", 'هراوة'],
                ['Rouiba', 'الرويبة'],
                ['Reghaïa', 'الرغاية'],
                ['Aïn Benian', 'عين البنيان'],
                ['Staoueli', 'سطاوالي'],
                ['Zeralda', 'زرالدة'],
                ['Mahelma', 'محالمة'],
                ['Rahmania', 'الرحمانية'],
                ['Souidania', 'السويدانية'],
                ['Cheraga', 'الشراقة'],
                ['Ouled Fayet', 'أولاد فايت'],
                ['El Achour', 'العاشور'],
                ['Draria', 'الدرارية'],
                ['Douera', 'الدويرة'],
                ['Baba Hassen', 'بابا حسن'],
                ['Khraissia', 'الخرايسية'],
                ['Saoula', 'السحاولة'],
            ],
        ],
        17 => [
            'fr' => 'Djelfa',
            'ar' => 'الجلفة',
            'communes' => [
                ['Djelfa', 'الجلفة'],
                ['Moudjebara', 'مجبارة'],
                ['Aïn Maabed', 'عين معبد'],
                ['Hassi Bahbah', 'حاسي بحبح'],
                ['Hassi El Euch', 'حاسي العش'],
                ['Zaafrane', 'الزعفران'],
                ['Aïn Oussera', 'عين وسارة'],
                ['Guernini', 'قرنيني'],
                ['Benhar', 'بنهار'],
                ['Messaad', 'مسعد'],
                ['Guettara', 'قطارة'],
                ['Deldoul', 'دلدول'],
                ['Sed Rahal', 'سد الرحال'],
                ['Selmana', 'سلمانة'],
                ['Aïn El Ibel', 'عين الإبل'],
                ['Tadmit', 'تعظميت'],
                ['Zaccar', 'زكار'],
                ['Charef', 'الشارف'],
                ['El Guedid', 'القديد'],
                ['Beni Yagoub', 'بني يعقوب'],
                ['El Idrissia', 'الإدريسية'],
                ['Douis', 'الدويس'],
                ['Aïn Chouhada', 'عين الشهداء'],
                ['Had Sahary', 'حد الصحاري'],
                ['Bouira Lahdab', 'بويرة الأحداب'],
                ['Birine', 'بيرين'],
                ['Oum Laadham', 'أم العظام'],
                ['Dar Chioukh', 'دار الشيوخ'],
                ["M'Liliha", 'مليليحة'],
                ['Sidi Baizid', 'سيدي بايزيد'],
                ['Sidi Ladjel', 'سيدي لعجال'],
                ['Hassi Fedoul', 'حاسي فدول'],
                ['El Khemis', 'الخميس'],
                ['Faidh El Botma', 'فيض البطمة'],
                ['Amourah', 'عمورة'],
                ['Aïn Feka', 'عين افقه'],
            ],
        ],
        18 => [
            'fr' => 'Jijel',
            'ar' => 'جيجل',
            'communes' => [
                ['Jijel', 'جيجل'],
                ['Erraguene Souissi', 'إراقن السويسي'],
                ['El Aouana', 'العوانة'],
                ['Ziama Mansouriah', 'زيامة منصورية'],
                ['Taher', 'الطاهير'],
                ['Emir Abdelkader', 'الأمير عبد القادر'],
                ['Chekfa', 'الشقفة'],
                ['Chahna', 'الشحنة'],
                ['El Milia', 'الميلية'],
                ['Sidi Maarouf', 'سيدي معروف'],
                ['Settara', 'السطارة'],
                ['El Ancer', 'العنصر'],
                ['Sidi Abdelaziz', 'سيدي عبد العزيز'],
                ['Kaous', 'قاوس'],
                ['Ghebala', 'غبالة'],
                ['Bouraoui Belhadef', 'بوراوي بلهادف'],
                ['Djimla', 'جيملة'],
                ['Selma Benziada', 'سلمى بن زيادة'],
                ['Boussif Ouled Askeur', 'بوسيف أولاد عسكر'],
                ['El Kennar Nouchfi', 'القنار نشفي'],
                ['Ouled Yahia Khedrouche', 'أولاد يحيى خدروش'],
                ['Boudria Beni Yadjis', 'بودريعة بني ياجيس'],
                ['Kheiri Oued Adjoul', 'خيري وادي عجول'],
                ['Texenna', 'تاكسنة'],
                ['Djemaa Beni Habibi', 'الجمعة بني حبيبي'],
                ['Bordj Tahar', 'برج الطهر'],
                ['Ouled Rabah', 'أولاد رابح'],
                ['Ouadjana', 'وجانة'],
            ],
        ],
        19 => [
            'fr' => 'Sétif',
            'ar' => 'سطيف',
            'communes' => [
                ['Sétif', 'سطيف'],
                ['Aïn El Kebira', 'عين الكبيرة'],
                ['Beni Aziz', 'بني عزيز'],
                ['Ouled Sidi Ahmed', 'أولاد سيدي أحمد'],
                ['Boutaleb', 'بوطالب'],
                ['Aïn Roua', 'عين الروى'],
                ['Draa Kebila', 'ذراع قبيلة'],
                ['Bir El Arch', 'بئر العرش'],
                ['Beni Chebana', 'بني شبانة'],
                ['Ouled Tebben', 'أولاد تبان'],
                ['Hamma', 'الحامة'],
                ['Maaouia', 'معاوية'],
                ['Aïn Legradj', 'عين لقراج'],
                ['Aïn Abessa', 'عين عباسة'],
                ['Dehamcha', 'الدهامشة'],
                ['Babor', 'بابور'],
                ['Guidjel', 'قجال'],
                ['Aïn Lahdjar', 'عين الحجر'],
                ['Bousselam', 'بوسلام'],
                ['El Eulma', 'العلمة'],
                ['Djemila', 'جميلة'],
                ['Beni Ouartilane', 'بني ورتيلان'],
                ['Rosfa', 'الرصفة'],
                ['Ouled Addouane', 'أولاد عدوان'],
                ['Belaa', 'بلاعة'],
                ['Aïn Arnat', 'عين أرنات'],
                ['Amoucha', 'عموشة'],
                ['Aïn Oulmene', 'عين ولمان'],
                ['Beidha Bordj', 'بيضاء برج'],
                ['Bouandas', 'بوعنداس'],
                ['Bazer Sakhra', 'بازر سكرة'],
                ['Hammam Essokhna', 'حمام السخنة'],
                ['Mezloug', 'مزلوق'],
                ['Bir Haddada', 'بئر حدادة'],
                ['Serdj El Ghoul', 'سرج الغول'],
                ['Harbil', 'حربيل'],
                ['El Ouricia', 'الأوريسيا'],
                ["Tizi N'Bechar", 'تيزي نبشار'],
                ['Salah Bey', 'صالح باي'],
                ['Aïn Azel', 'عين أزال'],
                ['Guenzet', 'قنزات'],
                ['Talaifacene', 'تالة إيفاسن'],
                ['Bougaa', 'بوقاعة'],
                ['Beni Fouda', 'بني فودة'],
                ['Tachouda', 'تاشودة'],
                ['Beni Mouhli', 'بني موحلي'],
                ['Ouled Sabor', 'أولاد صابر'],
                ['Guellal', 'قلال'],
                ['Aïn Sebt', 'عين السبت'],
                ['Hammam Guergour', 'حمام قرقور'],
                ['Aït Naoual Mezada', 'آيت نوال مزادة'],
                ['Ksar El Abtal', 'قصر الأبطال'],
                ['Beni Hocine', 'بني حسين'],
                ['Aït Tizi', 'آيت تيزي'],
                ['Maoklane', 'ماوكلان'],
                ['Guelta Zerka', 'قلتة زرقاء'],
                ['Oued El Bared', 'وادي البارد'],
                ['Taya', 'الطاية'],
                ['El Ouldja', 'الولجة'],
                ['Tella', 'تلة'],
            ],
        ],
        20 => [
            'fr' => 'Saïda',
            'ar' => 'سعيدة',
            'communes' => [
                ['Saïda', 'سعيدة'],
                ['Doui Thabet', 'دوي ثابت'],
                ['Aïn El Hadjar', 'عين الحجر'],
                ['Ouled Khaled', 'أولاد خالد'],
                ['Moulay Larbi', 'مولاي العربي'],
                ['Youb', 'يوب'],
                ['Hounet', 'هونت'],
                ['Sidi Amar', 'سيدي أعمر'],
                ['Sidi Boubekeur', 'سيدي بوبكر'],
                ['El Hassasna', 'الحساسنة'],
                ['Maamora', 'المعمورة'],
                ['Sidi Ahmed', 'سيدي أحمد'],
                ['Aïn Sekhouna', 'عين السخونة'],
                ['Ouled Brahim', 'أولاد إبراهيم'],
                ['Tircine', 'تيرسين'],
                ['Aïn Soltane', 'عين السلطان'],
            ],
        ],
        21 => [
            'fr' => 'Skikda',
            'ar' => 'سكيكدة',
            'communes' => [
                ['Skikda', 'سكيكدة'],
                ['Aïn Zouit', 'عين زويت'],
                ['El Hadaiek', 'الحدائق'],
                ['Azzaba', 'عزابة'],
                ['Djendel Saadi Mohamed', 'جندل سعدي محمد'],
                ['Aïn Cherchar', 'عين شرشار'],
                ['Bekkouche Lakhdar', 'بكوش لخضر'],
                ['Ben Azzouz', 'بن عزوز'],
                ['Es Sebt', 'السبت'],
                ['Collo', 'القل'],
                ['Beni Zid', 'بني زيد'],
                ['Kerkera', 'كركرة'],
                ['Ouled Attia', 'أولاد عطية'],
                ['Oued Zehour', 'وادي الزهور'],
                ['Zitouna', 'الزيتونة'],
                ['El Harrouch', 'الحروش'],
                ['Zerdazas', 'زردازة'],
                ['Ouled Hebaba', 'أولاد حبابة'],
                ['Sidi Mezghiche', 'سيدي مزغيش'],
                ['Emdjez Edchich', 'امجاز الدشيش'],
                ['Beni Oulbane', 'بني ولبان'],
                ['Aïn Bouziane', 'عين بوزيان'],
                ['Ramdane Djamel', 'رمضان جمال'],
                ['Beni Bechir', 'بني بشير'],
                ['Salah Bouchaour', 'صالح بوالشعور'],
                ['Tamalous', 'تمالوس'],
                ['Aïn Kechra', 'عين قشرة'],
                ['Oum Toub', 'أم الطوب'],
                ['Bein El Ouiden', 'بين الويدان'],
                ['Filfila', 'فلفلة'],
                ['Cheraia', 'الشرايع'],
                ['Kanoua', 'قنواع'],
                ['El Ghedir', 'الغدير'],
                ['Bouchtata', 'بوشطاطة'],
                ['Ouldja Boulballout', 'ولجة بولبلوط'],
                ['Kheneg Mayoum', 'خناق مايون'],
                ['Hamadi Krouma', 'حمادي كرومة'],
                ['El Marsa', 'المرسى'],
            ],
        ],
        22 => [
            'fr' => 'Sidi Bel Abbès',
            'ar' => 'سيدي بلعباس',
            'communes' => [
                ['Sidi Bel Abbès', 'سيدي بلعباس'],
                ['Tessala', 'تسالة'],
                ['Sidi Brahim', 'سيدي إبراهيم'],
                ['Mostefa Ben Brahim', 'مصطفى بن إبراهيم'],
                ['Telagh', 'تلاغ'],
                ['Mezaourou', 'مزاورو'],
                ['Boukhanafis', 'بوخنفيس'],
                ['Sidi Ali Boussidi', 'سيدي علي بوسيدي'],
                ['Badredine El Mokrani', 'بدر الدين المقراني'],
                ['Marhoum', 'مرحوم'],
                ['Tafissour', 'تفسور'],
                ['Amarnas', 'عمارنة'],
                ['Tilmouni', 'تلموني'],
                ['Sidi Lahcene', 'سيدي لحسن'],
                ['Aïn Thrid', 'عين الثريد'],
                ['Makedra', 'مكدرة'],
                ['Tenira', 'تنيرة'],
                ['Moulay Slissen', 'مولاي سليسن'],
                ['El Hacaiba', 'الحصيبة'],
                ['Hassi Zehana', 'حاسي زهانة'],
                ['Tabia', 'طابية'],
                ['Merine', 'مرين'],
                ['Ras El Ma', 'رأس الماء'],
                ['Aïn Tindamine', 'عين تندمين'],
                ['Aïn Kada', 'عين قادة'],
                ['Mcid', 'مسيد'],
                ['Sidi Khaled', 'سيدي خالد'],
                ['Aïn El Berd', 'عين البرد'],
                ['Sfissef', 'سفيزف'],
                ['Aïn Adden', 'عين عدن'],
                ['Oued Taourira', 'وادي تاوريرة'],
                ['Dhaya', 'الضاية'],
                ['Zerouala', 'زروالة'],
                ['Lamtar', 'لمطار'],
                ['Sidi Chaib', 'سيدي شعيب'],
                ['Sidi Dahou de Zairs', 'سيدي دحو الزاير'],
                ['Oued Sebaa', 'وادي السبع'],
                ['Boudjebaa El Bordj', 'بوجبهة البرج'],
                ['Sehala Thaoura', 'سهالة الثورة'],
                ['Sidi Yacoub', 'سيدي يعقوب'],
                ['Sidi Hamadouche', 'سيدي حمادوش'],
                ['Belarbi', 'بلعربي'],
                ['Oued Sefioun', 'وادي سفيون'],
                ['Teghalimet', 'تغاليمت'],
                ['Ben Badis', 'بن باديس'],
                ['Sidi Ali Benyoub', 'سيدي علي بن يوب'],
                ['Chetouane Belaila', 'شيطوان البلايلة'],
                ['Bir El Hammam', 'بئر الحمام'],
                ['Taoudmout', 'تاودموت'],
                ['Redjem Demouche', 'رجم دموش'],
                ['Benachiba Chelia', 'بن عشيبة شليا'],
                ['Hassi Dahou', 'حاسي دحو'],
            ],
        ],
        23 => [
            'fr' => 'Annaba',
            'ar' => 'عنابة',
            'communes' => [
                ['Annaba', 'عنابة'],
                ['Berrahal', 'برحال'],
                ['El Hadjar', 'الحجار'],
                ['Sidi Amar', 'سيدي عمار'],
                ['El Bouni', 'البوني'],
                ['Oued El Aneb', 'وادي العنب'],
                ['Cheurfa', 'الشرفة'],
                ['Seraïdi', 'سرايدي'],
                ['Aïn Berda', 'عين الباردة'],
                ['Chetaibi', 'شطايبي'],
                ['Treat', 'التريعات'],
                ['El Eulma', 'العلمة'],
            ],
        ],
        24 => [
            'fr' => 'Guelma',
            'ar' => 'قالمة',
            'communes' => [
                ['Guelma', 'قالمة'],
                ['Nechmaya', 'نشماية'],
                ['Bouati Mahmoud', 'بوعاتي محمود'],
                ['Oued Zenati', 'وادي الزناتي'],
                ['Tamlouka', 'تاملوكة'],
                ['Oued Fragha', 'وادي فراغة'],
                ['Aïn Sandel', 'عين صندل'],
                ['Ras El Agba', 'رأس العقبة'],
                ['Dahouara', 'الدهوارة'],
                ['Belkheir', 'بلخير'],
                ['Ben Djerrah', 'بن جراح'],
                ['Bou Hamdane', 'بوحمدان'],
                ['Aïn Makhlouf', 'عين مخلوف'],
                ['Aïn Ben Beida', 'عين بن بيضاء'],
                ['Khezara', 'خزارة'],
                ['Beni Mezline', 'بني مزلين'],
                ['Bou Hachana', 'بوحشانة'],
                ['Guelaat Bou Sbaa', 'قلعة بوصبع'],
                ['Hammam Debagh', 'حمام دباغ'],
                ['Roknia', 'الركنية'],
                ['Sellaoua Announa', 'سلاوة عنونة'],
                ['Medjez Amar', 'مجاز عمار'],
                ['Bouchegouf', 'بوشقوف'],
                ['Heliopolis', 'هيليوبوليس'],
                ['Houari Boumediene', 'هواري بومدين'],
                ['Bordj Sabath', 'برج صباط'],
                ["Hammam N'Bails", 'حمام النبايل'],
                ['Oued Cheham', 'وادي الشحم'],
                ['Medjez Sfa', 'مجاز الصفاء'],
                ['Boumahra Ahmed', 'بومهرة أحمد'],
                ['Aïn Reggada', 'عين رقادة'],
                ['Aïn Larbi', 'عين العربي'],
                ['Aïn Hessania', 'عين حسانية'],
                ['Djeballah Khemissi', 'جبالة الخميسي'],
            ],
        ],
        25 => [
            'fr' => 'Constantine',
            'ar' => 'قسنطينة',
            'communes' => [
                ['Constantine', 'قسنطينة'],
                ['Hamma Bouziane', 'حامة بوزيان'],
                ['Ibn Badis', 'ابن باديس'],
                ['Zighoud Youcef', 'زيغود يوسف'],
                ['Didouche Mourad', 'ديدوش مراد'],
                ['El Khroub', 'الخروب'],
                ['Aïn Abid', 'عين عبيد'],
                ['Beni Hamiden', 'بني حميدان'],
                ['Ouled Rahmoune', 'أولاد رحمون'],
                ['Aïn Smara', 'عين السمارة'],
                ['Messaoud Boudjriou', 'مسعود بوجريو'],
                ['Ibn Ziad', 'ابن زياد'],
            ],
        ],
        26 => [
            'fr' => 'Médéa',
            'ar' => 'المدية',
            'communes' => [
                ['Médéa', 'المدية'],
                ['Aïn Boucif', 'عين بوسيف'],
                ['Aïn Ouksir', 'عين اقصير'],
                ['Aïssaouia', 'العيساوية'],
                ['Aziz', 'عزيز'],
                ['Baata', 'بعطة'],
                ['Benchicao', 'بن شكاو'],
                ['Beni Slimane', 'بني سليمان'],
                ['Berrouaghia', 'البرواقية'],
                ['Bir Ben Laabed', 'بئر بن عابد'],
                ['Boghar', 'بوغار'],
                ['Bouaiche', 'بوعيش'],
                ['Bouaichoune', 'بوعيشون'],
                ['Bouchrahil', 'بوشراحيل'],
                ['Boughezoul', 'بوغزول'],
                ['Bouskene', 'بوسكن'],
                ['Chahbounia', 'الشهبونية'],
                ['Chelalet El Adhaoura', 'شلالة العذاورة'],
                ['Cheniguel', 'شنيقل'],
                ['Derrag', 'دراق'],
                ['Deux Bassins', 'الحوضين'],
                ['Djouab', 'جواب'],
                ['Draa Essamar', 'ذراع السمار'],
                ['El Azizia', 'العزيزية'],
                ['El Guelbelkebir', 'القلب الكبير'],
                ['El Hamdania', 'الحمدانية'],
                ['El Omaria', 'العمارية'],
                ['El Ouinet', 'العوينات'],
                ['Hannacha', 'حناشة'],
                ['Kef Lakhdar', 'الكاف الأخضر'],
                ['Khams Djouamaa', 'خمس جوامع'],
                ['Ksar El Boukhari', 'قصر البخاري'],
                ['Medjebar', 'مجبر'],
                ['Meghraoua', 'مغراوة'],
                ['Mezerana', 'مزرانة'],
                ['Mfatha', 'مفاتحة'],
                ['Mihoub', 'ميهوب'],
                ['Ouamri', 'وامري'],
                ['Oued Harbil', 'وادي حربيل'],
                ['Ouled Antar', 'أولاد عنتر'],
                ['Ouled Bouachra', 'أولاد بوعشرة'],
                ['Ouled Brahim', 'أولاد إبراهيم'],
                ['Ouled Deide', 'أولاد دايد'],
                ['Ouled Hellal', 'أولاد هلال'],
                ['Ouled Maaref', 'أولاد معرف'],
                ['Oum El Djalil', 'أم الجليل'],
                ['Ouzera', 'وزرة'],
                ['Rebaia', 'الربعية'],
                ['Saneg', 'سانق'],
                ['Sedraia', 'سدرايا'],
                ['Seghouane', 'سغوان'],
                ['Si Mahdjoub', 'سي المحجوب'],
                ['Sidi Damed', 'سيدي دامد'],
                ['Sidi Errabia', 'سيدي الربيع'],
                ['Sidi Naamane', 'سيدي نعمان'],
                ['Sidi Zahar', 'سيدي زهار'],
                ['Sidi Ziane', 'سيدي زيان'],
                ['Souagui', 'السواقي'],
                ['Tablat', 'تابلاط'],
                ['Tafraout', 'تافراوت'],
                ['Tamesguida', 'تمسقيدة'],
                ['Tizi Mahdi', 'تيزي مهدي'],
                ['Tlatet Eddouair', 'ثلاثة الدواير'],
                ['Zoubiria', 'الزبيرية'],
            ],
        ],
        27 => [
            'fr' => 'Mostaganem',
            'ar' => 'مستغانم',
            'communes' => [
                ['Mostaganem', 'مستغانم'],
                ['Sayada', 'صيادة'],
                ['Fornaka', 'فرناكة'],
                ['Stidia', 'ستيدية'],
                ['Aïn Nouissy', 'عين نويصي'],
                ['Hassi Maameche', 'حاسي ماماش'],
                ['Aïn Tedles', 'عين تادلس'],
                ['Sour', 'سور'],
                ['Oued El Kheir', 'وادي الخير'],
                ['Sidi Bellater', 'سيدي بلعطار'],
                ['Kheir Eddine', 'خير الدين'],
                ['Sidi Ali', 'سيدي علي'],
                ['Abdelmalek Ramdane', 'عبد المالك رمضان'],
                ['Hadjadj', 'حجاج'],
                ['Nekmaria', 'نكمارية'],
                ['Sidi Lakhdar', 'سيدي لخضر'],
                ['Achaacha', 'عشعاشة'],
                ['Khadra', 'خضرة'],
                ['Bouguirat', 'بوقيراط'],
                ['Sirat', 'صيرات'],
                ['Aïn Sidi Cherif', 'عين سيدي شريف'],
                ['Mesra', 'ماسرة'],
                ['Mansourah', 'منصورة'],
                ['Souaflia', 'السوافلية'],
                ['Ouled Boughalem', 'أولاد بوغالم'],
                ['Ouled Maallah', 'أولاد مع الله'],
                ['Mazagran', 'مزغران'],
                ['Aïn Boudinar', 'عين بودينار'],
                ['Tazgait', 'تازقايت'],
                ['Safsaf', 'صفصاف'],
                ['El Hassiane', 'الحسيان'],
                ['Touahria', 'الطواهرية'],
            ],
        ],
        28 => [
            'fr' => "M'Sila",
            'ar' => 'المسيلة',
            'communes' => [
                ["M'Sila", 'المسيلة'],
                ['Aïn El Hadjel', 'عين الحجل'],
                ['Aïn El Melh', 'عين الملح'],
                ['Aïn Errich', 'عين الريش'],
                ['Aïn Fares', 'عين فارس'],
                ['Aïn Khadra', 'عين الخضراء'],
                ['Belaiba', 'بلعايبة'],
                ['Ben Srour', 'بن سرور'],
                ['Beni Ilmane', 'بني يلمان'],
                ['Benzouh', 'بن زوه'],
                ['Berhoum', 'برهوم'],
                ['Bir Foda', 'بئر الفضة'],
                ['Bou Saada', 'بوسعادة'],
                ['Bouti Sayah', 'بوطي السايح'],
                ['Chellal', 'شلال'],
                ['Dehahna', 'الدهاهنة'],
                ['Djebel Messaad', 'جبل مساعد'],
                ['El Hamel', 'الهامل'],
                ['El Houamed', 'الحوامد'],
                ['Hammam Dhalaa', 'حمام الضلعة'],
                ['Khettouti Sed El Djir', 'خطوطي سد الجير'],
                ['Khoubana', 'خبانة'],
                ["M'Cif", 'مسيف'],
                ["M'Tarfa", 'مطارفة'],
                ['Maadid', 'المعاضيد'],
                ['Maarif', 'معاريف'],
                ['Magra', 'مقرة'],
                ['Medjedel', 'مجدل'],
                ['Mohammed Boudiaf', 'محمد بوضياف'],
                ['Ouanougha', 'ونوغة'],
                ['Oued Chair', 'وادي الشعير'],
                ['Ouled Addi Guebala', 'أولاد عدي لقبالة'],
                ['Ouled Derradj', 'أولاد دراج'],
                ['Ouled Madhi', 'أولاد ماضي'],
                ['Ouled Mansour', 'أولاد منصور'],
                ['Ouled Sidi Brahim', 'أولاد سيدي إبراهيم'],
                ['Ouled Slimane', 'أولاد سليمان'],
                ['Oultem', 'ولتام'],
                ['Sidi Aissa', 'سيدي عيسى'],
                ['Sidi Ameur', 'سيدي عامر'],
                ['Sidi Hadjeres', 'سيدي هجرس'],
                ["Sidi M'Hamed", 'سيدي امحمد'],
                ['Slim', 'سليم'],
                ['Souamaa', 'الصوامع'],
                ['Tamsa', 'تامسة'],
                ['Tarmount', 'تارمونت'],
                ['Zarzour', 'زرزور'],
            ],
        ],
        29 => [
            'fr' => 'Mascara',
            'ar' => 'معسكر',
            'communes' => [
                ['Mascara', 'معسكر'],
                ['Aïn Fares', 'عين فارس'],
                ['Aïn Fekan', 'عين فكان'],
                ['Aïn Ferah', 'عين فراح'],
                ['Aïn Fras', 'عين فراس'],
                ['Alaimia', 'العلايمية'],
                ['Aouf', 'عوف'],
                ['Beniane', 'بنيان'],
                ['Bou Hanifia', 'بوحنيفية'],
                ['Bou Henni', 'بوهني'],
                ['Chorfa', 'الشرفاء'],
                ['El Bordj', 'البرج'],
                ['El Gaada', 'القعدة'],
                ['El Ghomri', 'الغمري'],
                ['El Gueitena', 'القيطنة'],
                ['El Hachem', 'الحشم'],
                ['El Keurt', 'الكرط'],
                ['El Menaouer', 'المناور'],
                ['Ferraguig', 'فراقيق'],
                ['Froha', 'فروحة'],
                ['Gharrous', 'غروس'],
                ['Ghriss', 'غريس'],
                ['Guerdjoum', 'قرجوم'],
                ['Hacine', 'حسين'],
                ['Khalouia', 'الخلوية'],
                ['Makdha', 'ماكدة'],
                ['Mamounia', 'المامونية'],
                ['Maoussa', 'ماوسة'],
                ['Matemore', 'المطمر'],
                ['Mocta Douz', 'مقطع الدوز'],
                ['Mohammadia', 'المحمدية'],
                ['Nesmot', 'نسمط'],
                ['Oggaz', 'عقاز'],
                ['Oued El Abtal', 'وادي الأبطال'],
                ['Oued Taria', 'وادي التاغية'],
                ['Ras El Aïn Amirouche', 'رأس عين عميروش'],
                ['Sedjerara', 'سجرارة'],
                ['Sehailia', 'السهايلية'],
                ['Sidi Abdeldjebar', 'سيدي عبد الجبار'],
                ['Sidi Abdelmoumene', 'سيدي عبد المؤمن'],
                ['Sidi Boussaid', 'سيدي بوسعيد'],
                ['Sidi Kada', 'سيدي قادة'],
                ['Sig', 'سيق'],
                ['Tighennif', 'تيغنيف'],
                ['Tizi', 'تيزي'],
                ['Zahana', 'زهانة'],
                ['Zelamta', 'زلامطة'],
            ],
        ],
        30 => [
            'fr' => 'Ouargla',
            'ar' => 'ورقلة',
            'communes' => [
                ['Ouargla', 'ورقلة'],
                ['Aïn Beida', 'عين البيضاء'],
                ["N'Goussa", 'انقوسة'],
                ['Hassi Messaoud', 'حاسي مسعود'],
                ['Rouissat', 'الرويسات'],
                ['El Borma', 'البرمة'],
                ['Hassi Ben Abdellah', 'حاسي بن عبد الله'],
                ['Sidi Khouiled', 'سيدي خويلد'],
            ],
        ],
        31 => [
            'fr' => 'Oran',
            'ar' => 'وهران',
            'communes' => [
                ['Oran', 'وهران'],
                ['Gdyel', 'قديل'],
                ['Bir El Djir', 'بئر الجير'],
                ['Hassi Bounif', 'حاسي بونيف'],
                ['Es Senia', 'السانية'],
                ['Arzew', 'أرزيو'],
                ['Bethioua', 'بطيوة'],
                ['Marsat El Hadjadj', 'مرسى الحجاج'],
                ['Aïn El Turk', 'عين الترك'],
                ['El Ançor', 'الأنصر'],
                ['Oued Tlelat', 'وادي تليلات'],
                ['Tafraoui', 'طفراوي'],
                ['Sidi Chami', 'سيدي الشحمي'],
                ['Boufatis', 'بوفاطيس'],
                ['Mers El Kebir', 'المرسى الكبير'],
                ['Bousfer', 'بوسفر'],
                ['El Karma', 'الكرمة'],
                ['El Braya', 'البرية'],
                ['Hassi Ben Okba', 'حاسي بن عقبة'],
                ['Ben Freha', 'بن فريحة'],
                ['Hassi Mefsoukh', 'حاسي مفسوخ'],
                ['Sidi Ben Yebka', 'سيدي بن يبقى'],
                ['Misserghin', 'مسرغين'],
                ['Boutlelis', 'بوتليليس'],
                ['Aïn El Kerma', 'عين الكرمة'],
                ['Aïn El Bia', 'عين البية'],
            ],
        ],
        32 => [
            'fr' => 'El Bayadh',
            'ar' => 'البيض',
            'communes' => [
                ['El Bayadh', 'البيض'],
                ['Rogassa', 'روقاصة'],
                ['Stitten', 'ستيتن'],
                ['Brezina', 'بريزينة'],
                ['Ghassoul', 'الغاسول'],
                ['Boualem', 'بوعلام'],
                ['El Abiodh Sidi Cheikh', 'الأبيض سيدي الشيخ'],
                ['Aïn El Orak', 'عين العراك'],
                ['Arbaouat', 'أربوات'],
                ['Bougtoub', 'بوقطب'],
                ['El Kheither', 'الخيثر'],
                ['Kef El Ahmar', 'الكاف الأحمر'],
                ['Boussemghoun', 'بوسمغون'],
                ['Chellala', 'شلالة'],
                ['Kraakda', 'كراكدة'],
                ['El Bnoud', 'البنود'],
                ['Cheguig', 'شقيق'],
                ['Sidi Ameur', 'سيدي عامر'],
                ['El Mehara', 'المحرة'],
                ['Tousmouline', 'توسمولين'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ['Sidi Tifour', 'سيدي طيفور'],
            ],
        ],
        33 => [
            'fr' => 'Illizi',
            'ar' => 'إليزي',
            'communes' => [
                ['Illizi', 'إليزي'],
                ['Debdeb', 'دبداب'],
                ['Bordj Omar Driss', 'برج عمر إدريس'],
                ['In Amenas', 'عين أميناس'],
            ],
        ],
        34 => [
            'fr' => 'Bordj Bou Arréridj',
            'ar' => 'برج بوعريريج',
            'communes' => [
                ['Bordj Bou Arreridj', 'برج بوعريريج'],
                ['Ras El Oued', 'رأس الوادي'],
                ['Bordj Zemoura', 'برج زمورة'],
                ['Mansoura', 'المنصورة'],
                ["El M'hir", 'المهير'],
                ['Ben Daoud', 'بن داود'],
                ['El Achir', 'العشير'],
                ['Aïn Taghrout', 'عين تاغروت'],
                ['Bordj Ghdir', 'برج الغدير'],
                ['Sidi Embarek', 'سيدي امبارك'],
                ['El Hamadia', 'الحمادية'],
                ['Belimour', 'بليمور'],
                ['Medjana', 'مجانة'],
                ['Teniet En Nasr', 'ثنية النصر'],
                ['Djaafra', 'جعافرة'],
                ['El Main', 'الماين'],
                ['Ouled Brahem', 'أولاد ابراهم'],
                ['Ouled Dahmane', 'أولاد دحمان'],
                ['Hasnaoua', 'حسناوة'],
                ['Khelil', 'خليل'],
                ['Taglait', 'تقلعيت'],
                ['Ksour', 'القصور'],
                ['Ouled Sidi Brahim', 'أولاد سيدي إبراهيم'],
                ['Tafreg', 'تفرق'],
                ['Colla', 'القلة'],
                ['Tixter', 'تيكستار'],
                ['El Ach', 'العش'],
                ['El Anseur', 'العناصر'],
                ['Tesmart', 'تسامرت'],
                ['Aïn Tesra', 'عين تسرة'],
                ['Bir Kasdali', 'بئر قاصد علي'],
                ['Ghilassa', 'غيلاسة'],
                ['Rabta', 'الرابطة'],
                ['Haraza', 'حرازة'],
            ],
        ],
        35 => [
            'fr' => 'Boumerdès',
            'ar' => 'بومرداس',
            'communes' => [
                ['Boumerdès', 'بومرداس'],
                ['Boudouaou', 'بودواو'],
                ['Afir', 'أعفير'],
                ['Bordj Menaiel', 'برج منايل'],
                ['Baghlia', 'بغلية'],
                ['Sidi Daoud', 'سيدي داود'],
                ['Naciria', 'الناصرية'],
                ['Djinet', 'جنات'],
                ['Isser', 'يسر'],
                ['Zemmouri', 'زموري'],
                ['Si Mustapha', 'سي مصطفى'],
                ['Tidjelabine', 'تيجلابين'],
                ['Chabet El Ameur', 'شعبة العامر'],
                ['Thenia', 'الثنية'],
                ['Timezrit', 'تيمزريت'],
                ['Corso', 'قورصو'],
                ['Ouled Moussa', 'أولاد موسى'],
                ['Larbatache', 'الأربعطاش'],
                ['Bouzegza Keddara', 'بوزقزة قدارة'],
                ['Taourga', 'تاورقة'],
                ['Ouled Aïssa', 'أولاد عيسى'],
                ['Ben Choud', 'بن شود'],
                ['Dellys', 'دلس'],
                ['Ammal', 'عمال'],
                ['Beni Amrane', 'بني عمران'],
                ['Souk El Had', 'سوق الحد'],
                ['Boudouaou El Bahri', 'بودواو البحري'],
                ['Ouled Hedadj', 'أولاد هداج'],
                ['Leghata', 'لقاطة'],
                ['Hammedi', 'حمادي'],
                ['Khemis El Khechna', 'خميس الخشنة'],
                ['El Kharrouba', 'الخروبة'],
            ],
        ],
        36 => [
            'fr' => 'El Tarf',
            'ar' => 'الطارف',
            'communes' => [
                ['El Tarf', 'الطارف'],
                ['Bouhadjar', 'بوحجار'],
                ["Ben M'Hidi", 'بن مهيدي'],
                ['Bougous', 'بوقوس'],
                ['El Kala', 'القالة'],
                ['Aïn El Assel', 'عين العسل'],
                ['El Aioun', 'العيون'],
                ['Bouteldja', 'بوثلجة'],
                ['Souarekh', 'السوارخ'],
                ['Berrihane', 'بريحان'],
                ['Lac des Oiseaux', 'بحيرة الطيور'],
                ['Chefia', 'الشافية'],
                ['Drean', 'الذرعان'],
                ['Chihani', 'شيحاني'],
                ['Chebaita Mokhtar', 'شبيطة مختار'],
                ['Besbes', 'بسباس'],
                ['Asfour', 'عصفور'],
                ['Echatt', 'الشط'],
                ['Zerizer', 'زريزر'],
                ['Zitouna', 'الزيتونة'],
                ['Aïn Kerma', 'عين الكرمة'],
                ['Oued Zitoun', 'وادي الزيتون'],
                ['Hammam Beni Salah', 'حمام بني صالح'],
                ['Raml Souk', 'رمل السوق'],
            ],
        ],
        37 => [
            'fr' => 'Tindouf',
            'ar' => 'تندوف',
            'communes' => [
                ['Tindouf', 'تندوف'],
                ['Oum El Assel', 'أم العسل'],
            ],
        ],
        38 => [
            'fr' => 'Tissemsilt',
            'ar' => 'تيسمسيلت',
            'communes' => [
                ['Tissemsilt', 'تيسمسيلت'],
                ['Bordj Bou Naama', 'برج بونعامة'],
                ['Theniet El Had', 'ثنية الأحد'],
                ['Lazharia', 'الأزهرية'],
                ['Beni Chaib', 'بني شعيب'],
                ['Lardjem', 'لرجام'],
                ['Melaab', 'ملعب'],
                ['Sidi Lantri', 'سيدي العنتري'],
                ['Bordj El Emir Abdelkader', 'برج الأمير عبد القادر'],
                ['Layoune', 'العيون'],
                ['Khemisti', 'خميستي'],
                ['Ouled Bessem', 'أولاد بسام'],
                ['Ammari', 'عماري'],
                ['Youssoufia', 'اليوسفية'],
                ['Sidi Boutouchent', 'سيدي بوتوشنت'],
                ['Larbaa', 'الأربعاء'],
                ['Maasem', 'معاصم'],
                ['Sidi Abed', 'سيدي عابد'],
                ['Tamalaht', 'تملاحت'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ['Boucaid', 'بوقايد'],
                ['Beni Lahcene', 'بني لحسن'],
            ],
        ],
        39 => [
            'fr' => 'El Oued',
            'ar' => 'الوادي',
            'communes' => [
                ['El Oued', 'الوادي'],
                ['Robbah', 'الرباح'],
                ['Oued El Alenda', 'وادي العلندة'],
                ['Bayadha', 'البياضة'],
                ['Nakhla', 'النخلة'],
                ['Guemar', 'قمار'],
                ['Kouinine', 'كوينين'],
                ['Reguiba', 'الرقيبة'],
                ['Hamraia', 'الحمراية'],
                ['Taghzout', 'تغزوت'],
                ['Debila', 'الدبيلة'],
                ['Hassani Abdelkrim', 'حساني عبد الكريم'],
                ['Hassi Khalifa', 'حاسي خليفة'],
                ['Taleb Larbi', 'طالب العربي'],
                ['Douar El Ma', 'دوار الماء'],
                ['Sidi Aoun', 'سيدي عون'],
                ['Trifaoui', 'تريفاوي'],
                ['Magrane', 'المقرن'],
                ['Ben Guecha', 'بن قشة'],
                ['Ourmas', 'ورماس'],
                ['Mih Ouansa', 'اميه وانسة'],
                ['El Ogla', 'العقلة'],
            ],
        ],
        40 => [
            'fr' => 'Khenchela',
            'ar' => 'خنشلة',
            'communes' => [
                ['Khenchela', 'خنشلة'],
                ["M'Toussa", 'متوسة'],
                ['Kais', 'قايس'],
                ['Baghai', 'بغاي'],
                ['El Hamma', 'الحامة'],
                ['Aïn Touila', 'عين الطويلة'],
                ['Taouzianat', 'تاوزيانت'],
                ['Bouhmama', 'بوحمامة'],
                ['El Oueldja', 'الولجة'],
                ['Remila', 'الرميلة'],
                ['Cherchar', 'ششار'],
                ['Djellal', 'الجلال'],
                ['Babar', 'بابار'],
                ['Tamza', 'طامزة'],
                ['Ensigha', 'انسيغة'],
                ['Ouled Rechache', 'أولاد رشاش'],
                ['El Mahmal', 'المحمل'],
                ['Msara', 'مصارة'],
                ['Yabous', 'يابوس'],
                ['Khirane', 'خيران'],
                ['Chelia', 'شلية'],
            ],
        ],
        41 => [
            'fr' => 'Souk Ahras',
            'ar' => 'سوق أهراس',
            'communes' => [
                ['Souk Ahras', 'سوق أهراس'],
                ['Sedrata', 'سدراتة'],
                ['Hanancha', 'الحنانشة'],
                ['Mechroha', 'المشروحة'],
                ['Ouled Driss', 'أولاد إدريس'],
                ['Tiffech', 'تيفاش'],
                ['Zaarouria', 'الزعرورية'],
                ['Taoura', 'تاورة'],
                ['Drea', 'الدريعة'],
                ['Haddada', 'الحدادة'],
                ['Khedara', 'الخضارة'],
                ['Merahna', 'المراهنة'],
                ['Ouled Moumen', 'أولاد مومن'],
                ['Bir Bouhouche', 'بئر بوحوش'],
                ["M'Daourouch", 'مداوروش'],
                ['Oum El Adhaim', 'أم العظائم'],
                ['Aïn Zana', 'عين زانة'],
                ['Aïn Soltane', 'عين سلطان'],
                ['Ouillen', 'ويلان'],
                ['Sidi Fredj', 'سيدي فرج'],
                ['Safel El Ouiden', 'سافل الويدان'],
                ['Ragouba', 'الراقوبة'],
                ['Khemissa', 'خميسة'],
                ['Oued Kebrit', 'وادي الكبريت'],
                ['Terraguelt', 'تراقالت'],
                ['Zouabi', 'الزوابي'],
            ],
        ],
        42 => [
            'fr' => 'Tipaza',
            'ar' => 'تيبازة',
            'communes' => [
                ['Tipaza', 'تيبازة'],
                ['Menaceur', 'مناصر'],
                ['Larhat', 'لارهاط'],
                ['Douaouda', 'دواودة'],
                ['Bourkika', 'بورقيقة'],
                ['Khemisti', 'خميستي'],
                ['Aghbal', 'أغبال'],
                ['Hadjout', 'حجوط'],
                ['Sidi Amar', 'سيدي عمار'],
                ['Gouraya', 'قوراية'],
                ['Nador', 'الناظور'],
                ['Chaiba', 'شعيبة'],
                ['Aïn Tagourait', 'عين تاقورايت'],
                ['Cherchell', 'شرشال'],
                ['Damous', 'الداموس'],
                ['Meurad', 'مراد'],
                ['Fouka', 'فوكة'],
                ['Bou Ismail', 'بو إسماعيل'],
                ['Ahmer El Ain', 'أحمر العين'],
                ['Bou Haroun', 'بوهارون'],
                ['Sidi Ghiles', 'سيدي غيلاس'],
                ['Messelmoun', 'مسلمون'],
                ['Sidi Rached', 'سيدي راشد'],
                ['Kolea', 'القليعة'],
                ['Attatba', 'عطاطبة'],
                ['Sidi Semiane', 'سيدي سميان'],
                ['Beni Milleuk', 'بني ميلك'],
                ['Hadjeret Ennous', 'حجرة النص'],
            ],
        ],
        43 => [
            'fr' => 'Mila',
            'ar' => 'ميلة',
            'communes' => [
                ['Mila', 'ميلة'],
                ['Ferdjioua', 'فرجيوة'],
                ['Chelghoum Laid', 'شلغوم العيد'],
                ['Oued Athmenia', 'وادي العثمانية'],
                ['Aïn Mellouk', 'عين ملوك'],
                ['Telerghma', 'التلاغمة'],
                ['Oued Seguen', 'وادي سقان'],
                ['Tadjenanet', 'تاجنانت'],
                ['Benyahia Abderrahmane', 'بن يحيى عبد الرحمن'],
                ['Oued Endja', 'وادي النجاء'],
                ['Ahmed Rachedi', 'أحمد راشدي'],
                ['Ouled Khalouf', 'أولاد اخلوف'],
                ['Tiberguent', 'تيبرقنت'],
                ['Bouhatem', 'بوحاتم'],
                ['Rouached', 'الرواشد'],
                ['Tessala Lemtai', 'تسالة لمطاعي'],
                ['Grarem Gouga', 'القرارم قوقة'],
                ['Sidi Merouane', 'سيدي مروان'],
                ['Tassadane Haddada', 'تسدان حدادة'],
                ['Derradji Bousselah', 'دراجي بوصلاح'],
                ['Minar Zarza', 'مينار زارزة'],
                ['Amira Arras', 'أميرة أراس'],
                ['Terrai Bainen', 'ترعي باينان'],
                ['Hamala', 'حمالة'],
                ['Aïn Tine', 'عين التين'],
                ['El Mechira', 'المشيرة'],
                ['Sidi Khelifa', 'سيدي خليفة'],
                ['Zeghaia', 'زغاية'],
                ['Elayadi Barbes', 'العياضي برباس'],
                ['Aïn Beida Harriche', 'عين البيضاء أحريش'],
                ['Yahia Beniguecha', 'يحيى بني قشة'],
                ['Chigara', 'الشيقارة'],
            ],
        ],
        44 => [
            'fr' => 'Aïn Defla',
            'ar' => 'عين الدفلى',
            'communes' => [
                ['Aïn Defla', 'عين الدفلى'],
                ['Aïn Benian', 'عين بنيان'],
                ['Aïn Bouyahia', 'عين بويحيى'],
                ['Aïn Lechiakh', 'عين الأشياخ'],
                ['Aïn Soltane', 'عين سلطان'],
                ['Aïn Torki', 'عين التركي'],
                ['Arib', 'عريب'],
                ['Bathia', 'بطحية'],
                ['Belaas', 'بلعاص'],
                ['Ben Allal', 'بن علال'],
                ['Birbouche', 'بربوش'],
                ['Bir Ould Khelifa', 'بئر ولد خليفة'],
                ['Bordj Emir Khaled', 'برج الأمير خالد'],
                ['Boumedfaa', 'بومدفع'],
                ['Bourached', 'بوراشد'],
                ['Djelida', 'جليدة'],
                ['Djemaa Ouled Cheikh', 'الجمعة أولاد الشيخ'],
                ['Djendel', 'جندل'],
                ['El Abadia', 'العبادية'],
                ['El Amra', 'العامرة'],
                ['El Attaf', 'العطاف'],
                ['El Hassania', 'الحسانية'],
                ['El Maine', 'الماين'],
                ['Hammam Righa', 'حمام ريغة'],
                ['Hoceinia', 'الحسينية'],
                ['Khemis Miliana', 'خميس مليانة'],
                ['Mekhatria', 'المخاطرية'],
                ['Miliana', 'مليانة'],
                ['Oued Chorfa', 'وادي الشرفاء'],
                ['Oued Djemaa', 'وادي الجمعة'],
                ['Rouina', 'الروينة'],
                ['Sidi Lakhdar', 'سيدي لخضر'],
                ['Tacheta Zougagha', 'تاشتة زقاغة'],
                ['Tarik Ibn Ziad', 'طارق بن زياد'],
                ['Tiberkanine', 'تبركانين'],
                ['Zeddine', 'زدين'],
            ],
        ],
        45 => [
            'fr' => 'Naâma',
            'ar' => 'النعامة',
            'communes' => [
                ['Naâma', 'النعامة'],
                ['Mecheria', 'المشرية'],
                ['Aïn Sefra', 'عين الصفراء'],
                ['Tiout', 'تيوت'],
                ['Sfissifa', 'سفيسيفة'],
                ['Moghrar', 'مغرار'],
                ['Assela', 'عسلة'],
                ['Djeniene Bourezg', 'جنين بورزق'],
                ['Aïn Ben Khelil', 'عين بن خليل'],
                ['Makman Ben Amer', 'مكمن بن عمار'],
                ['Kasdir', 'القصدير'],
                ['El Biod', 'البيوض'],
            ],
        ],
        46 => [
            'fr' => 'Aïn Témouchent',
            'ar' => 'عين تموشنت',
            'communes' => [
                ['Aïn Témouchent', 'عين تموشنت'],
                ['Chaabet El Ham', 'شعبة اللحم'],
                ['Aïn Kihal', 'عين الكيحل'],
                ['Hammam Bouhadjar', 'حمام بوحجر'],
                ['Bou Zedjar', 'بوزجار'],
                ['Oued Berkeche', 'وادي برقش'],
                ['Aghlal', 'أغلال'],
                ['Terga', 'تارقة'],
                ['Aïn El Arbaa', 'عين الأربعاء'],
                ['Tamzoura', 'تامزورة'],
                ['Chentouf', 'شنتوف'],
                ['Sidi Ben Adda', 'سيدي بن عدة'],
                ['Aoubellil', 'عقب الليل'],
                ['El Malah', 'المالح'],
                ['Sidi Boumediene', 'سيدي بومدين'],
                ['Oued Sabah', 'وادي الصباح'],
                ['Ouled Boudjemaa', 'أولاد بوجمعة'],
                ['Aïn Tolba', 'عين الطلبة'],
                ['El Amria', 'العامرية'],
                ['Hassi El Ghella', 'حاسي الغلة'],
                ['Hassasna', 'الحساسنة'],
                ['Ouled Kihal', 'أولاد الكيحل'],
                ['Beni Saf', 'بني صاف'],
                ['Sidi Safi', 'سيدي صافي'],
                ['Oulhaca El Gheraba', 'ولهاصة الغرابة'],
                ['Tadmaya', 'تادمية'],
                ['El Emir Abdelkader', 'الأمير عبد القادر'],
                ['El Messaid', 'المساعيد'],
            ],
        ],
        47 => [
            'fr' => 'Ghardaïa',
            'ar' => 'غرداية',
            'communes' => [
                ['Ghardaïa', 'غرداية'],
                ['Dhayet Bendhahoua', 'ضاية بن ضحوة'],
                ['Berriane', 'بريان'],
                ['Metlili', 'متليلي'],
                ['El Guerrara', 'القرارة'],
                ['El Atteuf', 'العطف'],
                ['Zelfana', 'زلفانة'],
                ['Sebseb', 'سبسب'],
                ['Bounoura', 'بنورة'],
                ['Mansoura', 'المنصورة'],
            ],
        ],
        48 => [
            'fr' => 'Relizane',
            'ar' => 'غليزان',
            'communes' => [
                ['Relizane', 'غليزان'],
                ['Oued Rhiou', 'وادي ارهيو'],
                ['Belaassel Bouzegza', 'بلعسل بوزقزة'],
                ['Sidi Saada', 'سيدي سعادة'],
                ['Ouled Aiche', 'أولاد عيش'],
                ['Sidi Lazreg', 'سيدي لزرق'],
                ['El Hamadna', 'الحمادنة'],
                ["Sidi M'Hamed Ben Ali", 'سيدي امحمد بن علي'],
                ['Mediouna', 'مديونة'],
                ['Sidi Khettab', 'سيدي خطاب'],
                ['Ammi Moussa', 'عمي موسى'],
                ['Zemmoura', 'زمورة'],
                ['Beni Dergoun', 'بني درقن'],
                ['Djidiouia', 'جديوية'],
                ['El Guettar', 'القطار'],
                ['Hamri', 'حمري'],
                ['El Matmar', 'المطمر'],
                ["Sidi M'Hamed Ben Aouda", 'سيدي امحمد بن عودة'],
                ['Aïn Tarek', 'عين طارق'],
                ['Oued Essalem', 'وادي السلام'],
                ['Ouarizane', 'وريزان'],
                ['Mazouna', 'مازونة'],
                ['Kalaa', 'القلعة'],
                ['Aïn Rahma', 'عين الرحمة'],
                ['Yellel', 'يلل'],
                ['Oued El Djemaa', 'وادي الجمعة'],
                ['Ramka', 'رمكة'],
                ['Mendes', 'منداس'],
                ['Lahlef', 'لحلاف'],
                ['Beni Zentis', 'بني زنطيس'],
                ['Souk El Haad', 'سوق الحد'],
                ['Dar Ben Abdellah', 'دار بن عبد الله'],
                ['El Hassi', 'الحاسي'],
                ['Had Echkalla', 'حد الشكالة'],
                ['Bendaoud', 'بن داود'],
                ['El Ouldja', 'الولجة'],
                ['Merdja Sidi Abed', 'مرجة سيدي عابد'],
                ['Ouled Sidi Mihoub', 'أولاد سيدي الميهوب'],
            ],
        ],
        49 => [
            'fr' => 'Timimoun',
            'ar' => 'تيميمون',
            'communes' => [
                ['Timimoun', 'تيميمون'],
                ['Ouled Saïd', 'أولاد السعيد'],
                ['Aougrout', 'أوقروت'],
                ['Deldoul', 'دلدول'],
                ['Charouine', 'شروين'],
                ['Ouled Aïssa', 'أولاد عيسى'],
                ['Talmine', 'طالمين'],
                ['Ksar Kaddour', 'قصر قدور'],
                ['Tinerkouk', 'تينركوك'],
                ['Metarfa', 'المطارفة'],
            ],
        ],
        50 => [
            'fr' => 'Bordj Badji Mokhtar',
            'ar' => 'برج باجي مختار',
            'communes' => [
                ['Bordj Badji Mokhtar', 'برج باجي مختار'],
                ['Timiaouine', 'تيمياوين'],
            ],
        ],
        51 => [
            'fr' => 'Ouled Djellal',
            'ar' => 'أولاد جلال',
            'communes' => [
                ['Ouled Djellal', 'أولاد جلال'],
                ['Sidi Khaled', 'سيدي خالد'],
                ['Doucen', 'الدوسن'],
                ['Chaïba', 'الشعيبة'],
                ['Besbes', 'البسباس'],
                ['Ras El Miaad', 'رأس الميعاد'],
            ],
        ],
        52 => [
            'fr' => 'Béni Abbès',
            'ar' => 'بني عباس',
            'communes' => [
                ['Béni Abbès', 'بني عباس'],
                ['Igli', 'إقلي'],
                ['Tamtert', 'تامترت'],
                ['El Ouata', 'الواتة'],
                ['Kerzaz', 'كرزاز'],
                ['Timoudi', 'تيمودي'],
                ['Ksabi', 'القصابي'],
                ['Ouled Khoudir', 'أولاد خضير'],
                ['Beni Ikhlef', 'بني يخلف'],
            ],
        ],
        53 => [
            'fr' => 'In Salah',
            'ar' => 'عين صالح',
            'communes' => [
                ['In Salah', 'عين صالح'],
                ['In Ghar', 'إن غر'],
                ['Foggaret Ezzaouia', 'فقارة الزوى'],
            ],
        ],
        54 => [
            'fr' => 'In Guezzam',
            'ar' => 'عين قزام',
            'communes' => [
                ['In Guezzam', 'عين قزام'],
                ['Tin Zaouatine', 'تين زواتين'],
            ],
        ],
        55 => [
            'fr' => 'Touggourt',
            'ar' => 'تقرت',
            'communes' => [
                ['Touggourt', 'تقرت'],
                ['Nezla', 'النزلة'],
                ['Tebesbest', 'تبسبست'],
                ['Zaouia El Abidia', 'الزاوية العابدية'],
                ['Blidet Amor', 'بليدة عمر'],
                ['Temacine', 'تماسين'],
                ['Megarine', 'المقارين'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ["M'Naguer", 'المنقر'],
                ['El Hadjira', 'الحجيرة'],
                ['El Allia', 'العالية'],
                ['Taibet', 'الطيبات'],
                ['Benaceur', 'بن ناصر'],
            ],
        ],
        56 => [
            'fr' => 'Djanet',
            'ar' => 'جانت',
            'communes' => [
                ['Djanet', 'جانت'],
                ['Bordj El Haouas', 'برج الحواس'],
            ],
        ],
        57 => [
            'fr' => "El M'Ghair",
            'ar' => 'المغير',
            'communes' => [
                ["El M'Ghair", 'المغير'],
                ['Djamaa', 'جامعة'],
                ['Sidi Amrane', 'سيدي عمران'],
                ['Oum Touyour', 'أم الطيور'],
                ["M'Rara", 'المرارة'],
                ['Sidi Khellil', 'سيدي خليل'],
                ['Still', 'سطيل'],
                ['Tenedla', 'تندلة'],
            ],
        ],
        58 => [
            'fr' => 'El Meniaa',
            'ar' => 'المنيعة',
            'communes' => [
                ['El Meniaa', 'المنيعة'],
                ['Hassi Gara', 'حاسي القارة'],
                ['Hassi Fehal', 'حاسي الفحل'],
            ],
        ],
    ];
}
